resources:
  - ../../base

namePrefix: postprod-

commonLabels:
  environment: post-production

patches:
  - target:
      kind: Deployment
      name: shift-roaster-shift-roaster
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
